### ISSUE TITLE
[bug] Website has a scroll bar on the X axis

### ISSUE THREAD

**Issue by abitsalihu** [brittanyjoiner15/eui-event-template#40] opened 2022-09-27 15:18 UTC
While checking the website I noticed that the website - `body` overflows on the `x` axis, and there is no need to overflow since there isn't extra content on the right side and it makes the `UI` worse.

An easy solution would be adding a `overflow-x: hidden;` on the body tag, or you can find the element which is expanding the website and fix that! 

If you want the problem fixed through `css` I'm happy to do it, but if you want to do it through `React` then I'm sorry I still don't know that framework. :)

Video of the issue: 

https://user-images.githubusercontent.com/94648837/192566465-27869a2f-8958-4264-9bca-700f5149e7b9.mov

**Comment by brittanyjoiner15** [comment] 2022-09-27 15:26
@abitsalihu good catch! and yes fixing through CSS is just fine! I can assign this to you!

Let me know if you need any help with react. But basically build the CSS class and you can apply it to the component with the `className="yourClass"` prop

**Comment by abitsalihu** [comment] 2022-09-27 15:28
@brittanyjoiner15 thanks, I'll let you know If i have any problems. :)

**Comment by brittanyjoiner15** [comment] 2022-09-27 15:33
@abitsalihu great! thanks for taking this one!

**Comment by abitsalihu** [comment] 2022-09-27 15:55
@brittanyjoiner15 I think you have to assign this issue to someone else as I'm having problems with running the scripts in the terminal, and I think it's a problem with my laptop and not the repo (I looked for many solutions but so far none are working).

Below is the problem I'm having with the script:

<img width="1440" alt="Screen Shot 2022-09-27 at 17 52 11" src="https://user-images.githubusercontent.com/94648837/192575338-8c0aa78d-3444-4bf4-9655-a253026f9506.png">

**Comment by brittanyjoiner15** [comment] 2022-09-27 16:02
@abitsalihu hmm - maybe i have the wrong command in the docs! try running `yarn` and then `yarn start` and see if it runs

**Comment by abitsalihu** [comment] 2022-09-27 16:08
@brittanyjoiner15 No the commands are fine, it says that the command is not found in the `/bin/sh:` but as you can see on the right side inside the VS the script is there. I read that sometimes the module doesn't install fully or something and you have to `delete` it and reinstall, I did that like 5 times but no luck. If you find a solution that might help me feel free to send it to me, but maybe it's better you assign this to someone else and save the headaches from me. 😅

**Comment by brittanyjoiner15** [comment] 2022-09-27 16:12
@abitsalihu haha no worries i understand - im the same way if i can't get a repo running 😂 Sometimes I'll try deleting the repo and everything and trying it all from scratch and it works 🤷 but i don't have any other ideas aside from that. Weird since like you said it's right there.

If you think you know the code changes needed here, you're welcome to edit the files and make a PR and i can run it locally and confirm it works! Otherwise, i can unassign for now!

**Comment by abitsalihu** [comment] 2022-09-27 16:23
@brittanyjoiner15 I tried trying from scratch as well but no luck, maybe better to assign someone else to this. 

I will definitely check into this later and see why it was not working tho, and after I figure it out I'll check for another issue. :)

**Comment by brittanyjoiner15** [comment] 2022-09-27 16:26
@abitsalihu sounds good!! thanks and just create another issue if you wanna get to the bottom of this and I'll rope in some other devs to help us figure out what's going on : )

**Comment by AyushK-101** [comment] 2022-09-28 05:16
I would like to work on this issue

**Comment by ashishpetwal** [comment] 2022-09-28 07:24
Hey, @brittanyjoiner15 I have worked on this issue and kind of resolved it!

I would love to take this issue as part of HacktoberFest 2022. Kindly, assign it to me!

**Comment by brittanyjoiner15** [comment] 2022-09-28 13:53
@ashishpetwal im so sorry, i saw @AyushK-101 's comment before yours so I'm going to assign to them, but you're welcome to pair with them on it or if they're unable to take it then you can have it!

**Comment by brittanyjoiner15** [comment] 2022-09-28 13:54
@AyushK-101 just assigned to you!

**Comment by ashishpetwal** [comment] 2022-09-28 14:08
@brittanyjoiner15 that's completely fine bro! Will help if needed

**Comment by ashishpetwal** [comment] 2022-10-01 10:42
@brittanyjoiner15  and  @AyushK-101 kindly update if the issue is resolved or not !

**Comment by brittanyjoiner15** [comment] 2022-10-01 17:04
@AyushK-101 hey there! have you had a chance to work on this?

**Comment by AyushK-101** [comment] 2022-10-02 11:12
Working on it, will drop a message if I need help

**Closed as completed** 2022-10-02 13:19 UTC
Labels: bug, good first issue, hacktoberfest, up for grabs
