### ISSUE TITLE
As a user, I can update a Google Sheet with speaker info and it reflect on the speaker page

### ISSUE THREAD

**Issue by brittanyjoiner15** [brittanyjoiner15/eui-event-template#19] opened 2022-09-16 03:11 UTC
This is bit more of an advanced issue, but it would be really cool to hook up Google Sheet API to create a new card for each row in a spreadsheet tab that has speaker details. 

Ideally the spreadsheet has columns for: 

*  name: 
* title: 
* team
* location
* short bio
* pronounce
* image link

And the app is updated to create a EuiCard from each row with that data. 

As part of this issue, please update the documentation on the readme for how to run this locally and any necessary steps to configure and hook up your own spreadsheet.

This might also help : https://dev.to/varshithvhegde/easy-way-to-create-your-own-api-for-free-1mbc

**Comment by PrathamGwari** [comment] 2022-09-21 16:42
Hi @brittanyjoiner15 , the issue looks interesting to work on. Can you please assign this issue to me. 

I want this to be part of my contribution to hacktoberfest 2022, so can I generate a pull request in October?

**Comment by brittanyjoiner15** [comment] 2022-09-21 16:45
@PrathamGwari yes! that is fine, I know this is a bit of a bigger issue anyways and might take a bit to get going on anyways! Would love your help with this! Will go ahead and assign to you. If you can just post every couple days in here and let me know you're still interested in it/working on it, that would be great!

**Comment by PrathamGwari** [comment] 2022-09-21 16:51
Thanks @brittanyjoiner15 😄

**Comment by SahilAnower** [comment] 2022-09-28 14:16
Hi @PrathamGwari could you please elaborate the things you have added until now, and what are you using so that I can also use the same Google Sheet API?

**Comment by PrathamGwari** [comment] 2022-09-28 14:25
@SahilAnower 
I looked up for some solutions and founds a website called "sheets.best" which is an easy solution for this sort of problems. But the problem is that the service is paid. 

So I have decided to use google sheets api to read data from a file. Currently I am testing if the solution will work or not.

**Comment by SahilAnower** [comment] 2022-09-28 14:36
@PrathamGwari 
Yeah same here. I also got one but paid, only 500 requests per month. Google sheets api is good and fine. But when we are sending post data through their, it is showing CORS error. And i am also testing out let's see.

**Comment by brittanyjoiner15** [comment] 2022-09-28 14:49
@PrathamGwari and @SahilAnower thank you both for working on this! loving the progress!

**Comment by PrathamGwari** [comment] 2022-09-29 15:51
https://user-images.githubusercontent.com/75363815/193078044-d71020df-7e0a-48b6-8894-9613626c4a75.mp4
Here is a working demo. I have created a simple react app which makes an api call and fetches the data in excel sheet.

I have used google's app script to create a web application which contains a function to return sheet data in JSON form. 

The idea is that user will be provided with code containing all the get and post API function.
The user creates a sheet and pastes all that code in the app script editor and deploys the app in just a few clicks.

After the successful deployment user receives a URL which will be the request URL used in react app.

According to me this is a better alternative because there is not API calls limit and its free.
@brittanyjoiner15 @SahilAnower Please let me know your thoughts.

**Comment by SahilAnower** [comment] 2022-09-29 17:57
@PrathamGwari Great! Can you please provide me the appscript url with the code?

**Comment by brittanyjoiner15** [comment] 2022-09-30 00:41
@PrathamGwari i think that approach makes sense to me! As long as we can just include some documentation that explains those steps, i think that makes sense and seems like a good way to go about it!

**Comment by PrathamGwari** [comment] 2022-09-30 03:01
@brittanyjoiner15 I will provide a proper documentation with steps to create a simple web app with Google's App Script in just a few clicks along with screenshots.

Let me know if you have any other suggestions. 😊

**Comment by brittanyjoiner15** [comment] 2022-09-30 16:44
@PrathamGwari yes that would be great thank you! The test will be if i can run it locally and do it on my own with the docs! I will probably also try to get someone else to try it as well so we can make sure they're as clear as possible!

**Closed as completed** 2022-10-02 21:52 UTC
Labels: hacktoberfest
